[gate]
currencyPairs = ['BTC_USDT', 'ETH_USDT', 'BNB_USDT', 'USDC_USDT', 'ADA_USDT', 'DOGE_USDT', 'MATIC_USDT', 'SOL_USDT', 'DOT_USDT', 'LTC_USDT', 'SHIB_USDT', 'AVAX_USDT', 'DAI_USDT', 'WBTC_USDT', 'UNI_USDT', 'LINK_USDT', 'ATOM_USDT', 'XMR_USDT']

[okx]
currencyPairs = ['BTC_USDT', 'ETH_USDT', 'BNB_USDT', 'USDC_USDT', 'ADA_USDT', 'DOGE_USDT', 'MATIC_USDT', 'SOL_USDT', 'DOT_USDT', 'LTC_USDT', 'SHIB_USDT', 'AVAX_USDT', 'DAI_USDT', 'WBTC_USDT', 'UNI_USDT', 'LINK_USDT', 'ATOM_USDT', 'XMR_USDT']

